int init();
int input(char *, char *, int);
int gettasklistsize(struct tarefa *);
int intinput(char *);
int createtask(struct tarefa *, char *,int);
int viewtask(struct tarefa *, char *, int *, int);
int edittask(struct tarefa *, char *,int);
int deletetask(struct tarefa *, char *, int);
int savedata(char *, struct tarefa *, int *);
int loaddata(char *, struct tarefa *, int *);