int init();
int input(char *text, char *str, int max_len);
int gettasklistsize(struct tarefa *tasklist);
int intinput(char *text);
int createtask(struct tarefa *tasklist, char *str,int maxtask);
int viewtask(struct tarefa *tasklist, char *str, int *specific, int *maxtask);
int edittask(struct tarefa *tasklist, char *str,int *maxtask);
int deletetask(struct tarefa *tasklist, char *str, int *maxtask);
int savedata(char *filename, struct tarefa *, int *);
int loaddata(char *filename, struct tarefa *, int *);